title: Sidebar
category: 8
disabled: true
fields:
  -
    -
      label: Teaser
      name: teasers
      type: data
      options: 
        -
          label: Linktext
          type: textfield
          name: linktext
          validation:
            Required: 1
        -
          label: Image
          type: file
          name: image
          validation:
            Required: 1
          meta:
            width: 300
            height: 150
        -
          label: Imagelink
          type: link
          name: imagelink
          tabs: page,external,email,asset
        -
          label: Link
          type: link
          name: link
          tabs: page,external,email,asset
          validation:
            Required: 1          
        - 
          label: Text
          type: rte
          name: text     
    -
      label: Boxes
      type: data
      name: boxes
      validation:
        Required: 1
      options:
        -
          label: Linktext
          type: textfield
          name: linktext
          validation:
            Required: 1         
        - 
          Label: Link
          type: link  
          name: link   
          tabs: page,external,email,asset
          validation:
            Required: 1
        -
          label: Add Box-Icon
          type: file
          name: image  
          meta:
            width: 66
            height: 55
        -
          label: Box-Icon Link
          type: link
          name: boxiconlink
          tabs: page,external,email,asset
    -
      label: List
      type: data
      name: list
      validation:
        Required: 1
      options: 
        -
          label: Linktext
          type: textfield
          name: linktext
          validation:
            Required: 1          
        -
          label: Link
          type: link
          name: link  
          tabs: page,external,email,asset
          validation:
            Required: 1