title: Headline (H1)
category: 1
fields:
  -
    -
      label: Headline
      type: textfield
      name: headline
      validation:
        Required: 1
    -
      label: Link
      type: link
      name: headlinelink  
      tabs: page,external,email,asset  
    -
      label: Activate anchor?
      name: anchor 
      type: checkbox
    -
      label: Anchor title
      name: anchortitle
      type: textfield
      if:
        anchor: [1]           
    -
      label: Centered?
      type: checkbox
      name: centered