Categories:
    1:
        prio: 30
        label: Text only
    2:
        prio: 60
        label: Including images
    3:
        prio: 90
        label: Carousels
    4:
        prio: 120
        label: Tables
    5:
        prio: 150
        label: Footer
    6:
        prio: 500
        label: Plugins
    7:
        prio: 1000
        label: Misc
    8:
        prio: 160
        label: Menu

Limitations:
    footer_firstrow:
        disabled:
            - _all
        enabled:
            - footer
    footer_secondrow:
        disabled:
            - _all
        enabled:
            - footer
    footer_copyright:
        disabled:
            - _all
        enabled:
            - plain
    menu_homegarden:
        disabled:
            - _all
        enabled:
            - sidebar
    menu_professional:
        disabled:
            - _all
        enabled:
            - sidebar
    menu_insidekaercher:
        disabled:
            - _all
        enabled:
            - navigation
    menu_services:
        disabled:
            - _all
        enabled:
            - navigation