title: Business Unit
category: 3
fields:
  -
    -
      label: Left column
      type: section
    -
      label: First row (smaller font size)
      type: textfield
      name: headlineleft
    -
      label: Second row (bigger font size)
      type: textfield
      name: subtitleleft
    -
      label: Link
      type: link
      name: linkleft
    -
      label: Text
      type: rte
      name: textleft
    -
      label: Right column
      type: section
    -
      label: First row (smaller font size)
      type: textfield
      name: headlineright
    -
      label: Second row (bigger font size)
      type: textfield
      name: subtitleright
    -
      label: Link
      type: link
      name: linkright      
    -
      label: Text
      type: rte
      name: textright