title: Image and Text (1:1, two columns)
category: 2
fields:
  -
    -
      label: Left column
      type: section
    -
      label: Image
      type: file
      name: image
      meta:
        width: 300
        height:   
    -
      label: Link on image
      type: link
      name: imagelink
      tabs: page,external,email,asset
    -
      label: Overwrite Alt Tag
      type: textfield
      name: overwrite_alt_tag
    -
      label: Headline
      type: textfield
      name: headline    
    -
      label: Link on the headline
      type: link
      name: headlinelink 
      tabs: page,external,email,asset                
    -
      label: Text
      type: rte
      name: text     
  -
    -
      label: Right column
      type: section
    -
      label: Image
      type: file
      name: image
      meta:
        width: 300
        height:  
    -
      label: Link the image
      type: link
      name: imagelink
      tabs: page,external,email,asset
    -
      label: Overwrite Alt Tag
      type: textfield
      name: overwrite_alt_tag
    -
      label: Headline
      type: textfield
      name: headline
    -
      label: Link on the headline
      type: link
      name: headlinelink
      tabs: page,external,email,asset
    -
      label: Text
      type: rte
      name: text
  -
    -
      label: Config
      type: section
    -
      label: Headline type
      type: select
      options:
        2: 2
        3: 3
        4: 4
        5: 5
        6: 6
      name: type
    -
      label: Border around the images?
      type: checkbox
      name: imageborder
    -
      label: Horizontal line below the content?
      name: horizontalruleone
      type: checkbox
    -
      label: Text on the left side of the image?
      type: checkbox
      name: textleft
    -
      label: Anchor
      type: section
    -
      label: Activate anchor?
      name: anchor
      type: checkbox
    -
      label: Anchor title
      name: anchortitle
      type: textfield
      if:
        anchor: [1]