title: Navigation
category: 8
disabled: true
fields:
  -
    -
      label: Image
      type: file
      name: image
      validation:
        Required: 1
      meta:
        width: 406
        height: 203
    -
      label: Image Link
      type: link
      name: imagelinktop
    -
      label: Headline
      type: textfield
      name: headline
      validation:
        Required: 1
    -
      label: Headlinelink
      type: link
      name: headlinelink        
    -
      label: List
      type: data
      name: items
      validation:
        Required: 1
      options:
        -
          label: Name (not visible in the frontend)
          type: textfieldsingle
          name: storage_title
          validation:
            Required: 1
        -           
          label: Content type
          type: select
          options:
            1: Primary (not indented)
            2: Secondary (indented)
          name: selectcontent
          validation:
            Required: 1             
        -
          Label: Linktext
          type: textfield
          name: linktext
          validation:
            Required: 1
          if:
            selectcontent: [1]            
        -
          label: Link
          type: link
          name: link 
          tabs: page,external,email,asset
          validation:
            Required: 1
          if:
            selectcontent: [1]           
        -
          label: Sublinktext
          type: textfield
          name: sublinktext 
          if:
            selectcontent: [1]             
        -
          label: Sublink
          type: link
          name: sublink  
          tabs: page,external,email,asset 
          if:
            selectcontent: [1]    
        -
          label: Sublinktext
          type: textfield
          name: sublinktextsolo
          validation:
            Required: 1
          if:
            selectcontent: [2]             
        -
          label: Sublink
          type: link
          name: sublinksolo  
          tabs: page,external,email,asset 
          if:
            selectcontent: [2]                   
    -
      label: More columns?
      type: checkbox
      name: morecolumns   
                                