title: Horizontal Rule
category: 7
fields:
  -
    -
      label: Horizontal Rule
      name: horizontalruleone
      type: checkbox
    -
      label: Visible In Mobile View?
      name: mobilehrnormal
      type: checkbox
    -
      label: Horizontal Rule (bold)
      name: horizontalrulebold
      type: checkbox       
    -
      label: Visible In Mobile View (bold)?
      name: mobilehrbold
      type: checkbox    
     
      
      
 
