title: HTML
category: 1
disabled: 1
fields:
  -
    -
      label: I know what I'm doing, am familiar in html and do know that this code can DESTROY the complete markup of the website.
      type: checkbox
      name: check
      validation:
        Required: 1
    -
      label: HTML
      type: section
    -
      label: HTML
      type: textarea
      name: html
      validation:
        Required: 1