title: 404 error page
category: 2
fields:
  -
    -
      label: Text
      type: section
    -
      label: Headline
      type: textfield
      name: headline
      validation:
        Required: 1
    -
      label: Text
      type: rte
      name: text
      validation:
        Required: 1
    -
      label: Image
      type: file
      name: image
      validation: 
        Required: 1
      meta:
        width: 620
        height:
    -
      label: Overwrite Alt Tag
      type: textfield
      name: overwrite_alt_tag
    -
      label: Text on button
      type: textfield
      name: buttontext
      validation:
        Required: 1
    -
      label: Link
      type: link
      name: link
      tabs: page
      validation:
        Required: 1