title: Text (full width)
category: 1
fields:
  -
    -
      label: Text
      type: rte
      name: text
      validation:
        Required: 1
    -
      label: Horizontal line below the text?
      name: horizontalruleone
      type: checkbox        
      