title: Button Pairs
category: 7
fields:
  -  
    -
      label: Color
      type: select
      options:
        1: Yellow
        2: Grey
      name: color
      validation:
        Required: 1    
    -
      label: Position
      type: select
      options:
        1: Left
        2: Middle
        3: Right
      name: position
      validation:
        Required: 1  
    -
      label: Button Pairs
      type: data
      name: items
      validation:
        Required: 1
      options:    
        -
          label: Name (not visible in the frontend)
          type: textfieldsingle
          name: storage_title
          validation:
            Required: 1           
        -
          label: Button 1 text
          name: buttontextone
          type: textfield
          validation:
            Required: 1 
        - 
          label: Button 1 link
          type: link      
          name: buttonlinkone
          tabs: page,external,email,asset
          validation:
            Required: 1 
        -
          label: Button 2 text
          name: buttontexttwo
          type: textfield
          validation:
            Required: 1 
        - 
          label: Button 2 link
          type: link      
          name: buttonlinktwo
          tabs: page,external,email,asset
          validation:
            Required: 1 